GET http://localhost:5000/posts/

###
GET http://localhost:5000/posts/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJUZXN0MSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2NzUyNDM4NTQsImV4cCI6MTY3NTI0NzQ1NH0.g8AgTSfayGn0hL3A9FnbQKw5Lry-uGmMXSamB1KA0Q8

{
    "username": "revin21"
}

###
POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Test1",
    "username": "test1",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login/
Content-Type: application/json

{
    "username": "revin21",
    "password": "123456"
}

###
GET http://localhost:5000/token/

###
DELETE http://localhost:5000/logout/

###
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eWUiOiJUZXN0MSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2NzUyNDM4NTQsImV4cCI6MTY3NTI0NzQ1NH0.g8AgTSfayGn0hL3A9FnbQKw5Lry-uGmMXSamB1KA0Q8

{
    "author": "Test1",
    "username": "test1",
    "content": "Hello! Iam Test1"
}

###
DELETE http://localhost:5000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJUZXN0MSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2NzUyNDM4NTQsImV4cCI6MTY3NTI0NzQ1NH0.g8AgTSfayGn0hL3A9FnbQKw5Lry-uGmMXSamB1KA0Q8

{
    "username": "revin21",
    "id": 8
}