GET http://localhost:5000/posts/

###
POST http://localhost:5000/posts/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSZXZpbiBEZW5uaXMgUiIsInVzZXJuYW1lIjoicmV2aW4yMSIsImlhdCI6MTY3NTQyNTI3NCwiZXhwIjoxNjc1NDI4ODc0fQ.L_8zZgefwFuYu8vAp1RRat5hj8zWeQ12T3fjYV993O8

{
    "username": "revin21"
}

###
POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Test1",
    "username": "test1",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login/
Content-Type: application/json

{
    "username": "revin21",
    "password": "123456"
}

###
GET http://localhost:5000/token/

###
DELETE http://localhost:5000/logout/

###
POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSZXZpbiBEZW5uaXMgUiIsInVzZXJuYW1lIjoicmV2aW4yMSIsImlhdCI6MTY3NTQyNTQ3OCwiZXhwIjoxNjc1NDI5MDc4fQ.qzEYiDsjZagErLzntYN9zQOC6rlAs2jvZCYGDS00BFE

{
    "author": "Revin Dennis Ramadhan",
    "username": "revin21",
    "content": "Hello !! My name is Revin!"
}

###
DELETE http://localhost:5000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJUZXN0MSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE2NzUyNDM4NTQsImV4cCI6MTY3NTI0NzQ1NH0.g8AgTSfayGn0hL3A9FnbQKw5Lry-uGmMXSamB1KA0Q8

{
    "username": "revin21",
    "id": 8
}

###
PUT http://localhost:5000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSZXZpbiBEZW5uaXMgUiIsInVzZXJuYW1lIjoicmV2aW4yMSIsImlhdCI6MTY3NTY1NTQwOCwiZXhwIjoxNjc1NjU5MDA4fQ.emROzeJnhdDjeYRon12Xpx_ZePK3qn0_pCiVN6Nt2ho

{
    "username": "revin21",
    "id": 15,
    "content": "Hello, my name is Revin Dennis R."
}